project_id = "llyunioulzfbgqvmeaxq"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://llyunioulzfbgqvmeaxq.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[functions.cardcom-webhook]
verify_jwt = false