project_id = "llyunioulzfbgqvmeaxq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://llyunioulzfbgqvmeaxq.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[functions.cardcom-webhook]
verify_jwt = false