
version: '3.8'

services:
  zap:
    image: owasp/zap2docker-stable
    container_name: zap-scanner
    volumes:
      - ./security:/zap/wrk/:rw
      - ./security/config:/zap/config/:ro
    networks:
      - zap-network
    environment:
      - ZAP_PORT=8080
    ports:
      - "8090:8080"  # ZAP GUI port
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

  # Your application (if you want to test in isolated environment)
  app:
    build: .
    container_name: amiram-academy-test
    ports:
      - "3000:8080"
    networks:
      - zap-network
    environment:
      - NODE_ENV=test

networks:
  zap-network:
    driver: bridge
