
-- Add premium and AI-generated question support to questions table
ALTER TABLE questions 
ADD COLUMN is_premium BOOLEAN DEFAULT FALSE,
ADD COLUMN ai_generated BOOLEAN DEFAULT FALSE,
ADD COLUMN generation_model TEXT,
ADD COLUMN batch_id TEXT,
ADD COLUMN quality_score NUMERIC;

-- Create index for efficient premium question filtering
CREATE INDEX idx_questions_premium ON questions(is_premium);
CREATE INDEX idx_questions_ai_generated ON questions(ai_generated);
CREATE INDEX idx_questions_batch_id ON questions(batch_id);

-- Add comment for documentation
COMMENT ON COLUMN questions.is_premium IS 'Whether this question requires premium subscription';
COMMENT ON COLUMN questions.ai_generated IS 'Whether this question was generated by AI';
COMMENT ON COLUMN questions.generation_model IS 'AI model used to generate the question';
COMMENT ON COLUMN questions.batch_id IS 'Batch identifier for bulk uploaded questions';
COMMENT ON COLUMN questions.quality_score IS 'Quality score from 0-100 for AI generated questions';
